version: '3.7'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  postgres:
    build:
      context: .
      dockerfile: ./dockerfiles/Postgres/Dockerfile
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: table_task_db
      POSTGRES_USER: debug
      POSTGRES_PASSWORD: debug
    image: postgres:12.7
    container_name: postgres_table_test
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z

  django:
    build:
      context: .
      dockerfile: ./dockerfiles/django/Dockerfile
    depends_on:
      - postgres
    container_name: django_table_test
    volumes:
      - .:/app:z
    ports:
      - "8003:8000"
    command: ./dockerfiles/django/start

  front-app:
    container_name: front-app
    build:
      context: .
      dockerfile: ./dockerfiles/front/Dockerfile
    volumes:
      - '.:/vue-front'
      - '/vue-front/node_modules'
    ports:
      - 8080:8080
    command: npm run serve
