# Generated by Django 4.0 on 2021-12-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('distance', models.IntegerField(verbose_name='Distance')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
